apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c8gr7xi7r-nodejs
  janus-idp.io/tekton: c8gr7xi7r-nodejs
  backstage.io/kubernetes-id: c8gr7xi7r-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c8gr7xi7r-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
